### ISSUE TITLE
✨ - Play next video automatically

### ISSUE THREAD

**Issue by RemiSaurel** [RemiSaurel/own-workspace#8]
Since some of the new videos are not live, when a music is finished it has to play the next one.

**Comment by LucasVbr** [comment]
Maybe you can use a [Youtube playlist](https://support.google.com/youtube/answer/171780?hl=en) to make it change automatically.

**Comment by RemiSaurel** [comment]
> Maybe you can use a [Youtube playlist](https://support.google.com/youtube/answer/171780?hl=en) to make it change automatically.

I think I'll look after [Youtube API](https://developers.google.com/youtube/v3) and try to use it since it allows you to have way better controls than I have rn.
